### PR TITLE
[FEAT] New Architecture Migration

### PR DESCRIPTION
**Pull request by cipolleschi**
## Summary
In this PR, we migrated the library to the New Architecture.

## TestPlan
We tried to test it by:
1. Creating a new React Native app: `npx react-native init NewArch`
2. installing the library: `cd NewArch && yarn add ../react-native-blob-util`
3. enabling the New Architecture:
    1. on iOS: `cd ios && bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`
    2. on Android: open the `gradle.properties` file and set the `newArchEnabled` flag to `true`.
4. Running the app: `npx react-native run-ios` and `npx react-native run-android`
5. Replacing the default `App.js` with the one we found in the `examples/ReactNativeBlobUtils`

## Next Steps
We will be happy to help you test the library further.
If you have any other way to test the library, let us know how to do it and we will schedule some time to do that! :D

### CODE REVIEW

**Comment by cipolleschi** [comment]
cc @cortinico who helped with the Android development

**Comment by RonRadtke** [comment]
Currently the oldarch doesn't work.
Testcase:
New project on RN 063 as suggested in the example app
Result: "TypeError: null is not an object (evaluating '_NativeBlobUtils.default.getConstants')"

It seems that the default export  in [codegenSpecs/NativeBlobUtils.js](https://github.com/RonRadtke/react-native-blob-util/pull/186/files#diff-422eaaac1637406fb46c2f165743b4ae04722a2d6fd371e8292c9d2a46c89ac8))is null

**Comment by cortinico** [comment]
> New project on RN 063 as suggested in the example app

Is this happening on Android or iOS?
Also does it reproduce on RN 070?

**Comment by RonRadtke** [comment]
> > New project on RN 063 as suggested in the example app
> 
> Is this happening on Android or iOS? Also does it reproduce on RN 070?

It's happening on Android (iOS not tested yet).
I'll test it later today on RN 070 and give you feedback about that

**Comment by RonRadtke** [comment]
@cortinico in RN 07 with newArchEnabled=false it works fine

**Comment by cortinico** [comment]
> @cortinico in RN 07 with newArchEnabled=false it works fine

That's great to hear. We'll have to bisect the RN versions to understand where it failed :(

**Comment by RonRadtke** [comment]
> > @cortinico in RN 07 with newArchEnabled=false it works fine
> 
> That's great to hear. We'll have to bisect the RN versions to understand where it failed :(

I'm checking in parallel...
RN 0.65.2 works as expected
RN 0.64.1 has the issue on the other hand

Upgrading to Gradle 6.9 doesn't do the trick - kinda had the hope for a bug here

**Comment by cortinico** [comment]
> I'll have to look into this next week

Sorry I haven't got the time to look into this yet @RonRadtke 
I'm also wondering if you would be fine just releasing a new version of `react-native-blob-util` mentioning that you support RN 0.64+ and point users to the latest stable version for 0.63 as 63 is quite of an old version.

**Comment by RonRadtke** [comment]
> > I'll have to look into this next week
> 
> Sorry I haven't got the time to look into this yet @RonRadtke I'm also wondering if you would be fine just releasing a new version of `react-native-blob-util` mentioning that you support RN 0.64+ and point users to the latest stable version for 0.63 as 63 is quite of an old version.

Hi - that's okay, thanks for answering regardless.
Yes, as I said on discord, I would be perfectly fine bumping the minimum version of RN to 0.64.+
Or even higher if you think there is a benefit in.  (I think one version increased the OkHTTP to v4, might be worth taking this one with directly too then)

**Comment by RonRadtke** [comment]
newarch on RN 0.70 on iOS is working fine
Oldarch on an older RN I'm still testing or better fighting with xcode

**Comment by cipolleschi** [comment]
Hi @RonRadtke, if you need help with your battle, I may help you. I had my fair shares of Xcode's fight!

**Comment by RonRadtke** [comment]
> Hi @RonRadtke, if you need help with your battle, I may help you. I had my fair shares of Xcode's fight!

Thank you - yeah Xcode is pain.
But I got it to work with RN0.64.1 and since we are planning to drop 0.63 that's fine.

So we are fine on iOS too. :) 

I'll create a pull-request on your branch later on to fix some issues and outdated definitions

**Comment by cipolleschi** [comment]
Hi @RonRadtke, is there anything I can do to help you with the PR? Is it about solving the conflicts of:
```
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtil.java
android/src/main/java/com/ReactNativeBlobUtil/ReactNativeBlobUtilReq.java
```

Or there is something more to do?

**Comment by RonRadtke** [comment]
Thanks. This pull request has been integrated manually.

**Comment by cipolleschi** [comment]
You are very welcome! :D 

Let us know how the testing goes and when it is released. If you also have an ETA, that would really helpful for our planning. 🙏 

Thank you so much!

**Comment by RonRadtke** [comment]
> You are very welcome! :D
> 
> Let us know how the testing goes and when it is released. If you also have an ETA, that would really helpful for our planning. 🙏
> 
> Thank you so much!

My plan is to get some documentation and readme etc done today. So my goal is to release it till tomorrow midnight (11.11 12am CET)

**Comment by RonRadtke** [comment]
@cipolleschi it's released :)

**Comment by feraswfares** [comment]
image


hello @RonRadtke 

still not working  on 

android 
RN 0.64.1
 react-native-blob-util: 0.17.0

**Comment by RonRadtke** [comment]
@feraswfares I know - we had to drop the 0.64 support. It is fairly old and it's more important to get the new arch supported than supporting an old react-native version.
But I obviously wrote the wrong version in the readme - sorry for that.

**Pull request closed without merging**
