### PR TITLE
Fix public directory

### PR DESCRIPTION
**Pull request by oneHamidreza**
Changed DCIMDir, PictureDir, MusicDir, DownloadDir, MovieDir, RingtoneDir, SDCardDir to `Environment.getExternalStoragePublicDirectory` path.

### CODE REVIEW

**Comment by SabbeAndres** [comment]
This fixed my download problem, thanks!

**Comment by RonRadtke** [comment]
You'll break the fix made in this commit: https://github.com/RonRadtke/react-native-blob-util/commit/ae998b2c62776d342b35f4c98ff9de795cae7353

Besides you would break Android > API 29 with this fix. So not going to merge it. Please fix it in a way that won't lead to additional problems / crashes.

**Comment by halaei** [comment]
Hello @RonRadtke. It seems that there is no need to check for null, because unlike `ctx.getExternalFilesDir()`, `Environment.getExternalStoragePublicDirectory()` doesn't return null, but may return a File which doesn't exist.

I am not sure if  `Environment.getExternalStoragePublicDirectory()` causes issue for API > 29. It is deprecated but still usable, isn't it?

My related issue: #89

**Comment by RonRadtke** [comment]
How about implementing an option like "legacypath" and this one will return the "old" version via `Environment.getExternalStoragePublicDirectory()` ?
That way we could make sure not not break anything and let the user decide which path he wants to use.

**Comment by afilp** [comment]
Does this PR allow us to download a PDF inside the common (public) `Downloads` instead of the "app-specific" "Downloads"? (in `Android -> data`

**Comment by RonRadtke** [comment]
Not in android >= 10

**Comment by RonRadtke** [comment]
I created a branch with changes to expose the old paths: https://github.com/RonRadtke/react-native-blob-util/tree/feature/legacypaths

@oneHamidreza @halaei what's your opinion about this way? Doable for you or any better suggestions?

**Comment by RonRadtke** [comment]
Fixed in https://github.com/RonRadtke/react-native-blob-util/releases/tag/0.16.2

**Pull request closed without merging**
