### PR TITLE
Change Android mv() back to using the system renameTo() method.

### PR DESCRIPTION
**Pull request by pcardon**
A previous change to rn-fetch-blob's mv implementation entailed copying the source file to the destination file and then deleting the source file.  This approach has an undesirable impact on the mv operation, where the operation takes orders of magnitude longer to complete.  It also adds disk space requirements that shouldn't be necessary, since both files need to exist at the same time.
This change goes back to using the renameTo() method, while adding some extra error checking to hopefully alleviate whatever problems caused the original fix.
Note that the POSIX mv() and rename() methods both stipulate that moving to a non-existent directory should be treated as an error.

### CODE REVIEW

**Comment by RonRadtke** [comment]
Can't find the original issue anymore either.
You tested your changes @pcardon ?

**Comment by pcardon** [comment]
Yes.  Our team has been using this code for at least a year.

**Comment by pcardon** [comment]
Thanks for the merges, Ron.  I'm happy to help with other issues.  Let's talk some time about how I could help.

**Comment by RonRadtke** [comment]
@pcardon thank you very much for the offer! Feel free to contact me. Best you just send me a mail to dev@ikascripts.de

**Pull request merged**
