### PR TITLE
Fix for RN 0.72.1

### PR DESCRIPTION
**Pull request by billnbell**
This PR fixes use_framework! for RN 0.72.1.

Please check it out. The path works on my PC - but errors if I don't change it.

### CODE REVIEW

**Comment by RonRadtke** [comment]
Could you maybe explain a little why you had to make these changes?
Did you try if the current version works in a new app with the new arch?

**Comment by billnbell** [comment]
Yeah the current version does not work when using `use_frameworks! :linkage => :static`

I get cannot find: `<React-Codegen/ReactNativeBlobUtilSpec/ReactNativeBlobUtilSpec.h>`

But if I add these changes (which is recommended anyways by React-Native team going forward) with `install_modules_dependencies(s)` - so that change it good to go.

I am unsure why React-Codegen is not finding the ReactNativeBlobUtilSpec.h file, but this works for me too.

#import <React-Codegen/ReactNativeBlobUtilSpec/ReactNativeBlobUtilSpec.h>
changed to:
#import <ReactNativeBlobUtilSpec/ReactNativeBlobUtilSpec.h>

**Comment by billnbell** [comment]
I would also recommend your switch example app to use `use_frameworks! :linkage => :static` since most people using New Arch is using that since RN-Firebase requires it now.

**Comment by RonRadtke** [comment]
Does the changes still work without the !use_framework?

**Comment by billnbell** [comment]
yes it still works - in RN 72+. Otherwise wrap the `install_modules_dependencies(s)` with `if use_fabric`

**Comment by RonRadtke** [comment]
I'll merge it this week and bring it live as 0.19.0.
Just have to go trough the documentation in the reactwg

**Pull request merged**
